apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulse-monitoring

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml

commonLabels:
  app: pulse
  managed-by: kustomize

images:
  - name: pulse-monitor/pulse
    newTag: latest

configMapGenerator:
  - name: pulse-config
    behavior: merge
    literals:
      - PULSE_LOG_LEVEL=info
      - PULSE_LOG_FORMAT=json
