apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulse-data
  namespace: pulse-monitoring
  labels:
    app: pulse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
